FROM ubuntu:22.04

RUN apt update -y
RUN apt install -y cmake
RUN apt install -y nano
RUN apt install -y openjdk-17-jdk

COPY lingua-franca /lf/lingua-franca
COPY k22f-support /lf/k22f-support
COPY install/gcc-arm-none-eabi-10.3-2021.10 /opt/gcc-arm-none-eabi-10.3-2021.10

ENV ARMGCC_DIR="/opt/gcc-arm-none-eabi-10.3-2021.10"

ENTRYPOINT ["/lf/lingua-franca/bin/lfc"]
